spring:
  application:
    name: eureka-server-peer1
server:
  port: 20001
eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: false # 是否发起服务注册
    service-url:
      defaultZone: http://peer2:20000/eureka/ # 注册中心
