spring:
  application:
    name: gateway-sample
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  # 路由中的大小转为小写： 正常是 http://localhost:65000/FEIGN-CLIENT/sayHi  开启后 http://localhost:65000/feign-client/sayHi
      routes:  # 断言配置
        - id: qq
          uri: https://www.qq.com
          predicates:
            - Path=/qq/**
          filters:
            - StripPrefix=1

        - id: feignclient
          uri: lb://FEIGN-CLIENT
          predicates:
            - Path=/yml/**
          filters:
            - StripPrefix=1 # //localhost:9000/yml/sayHi 会切割前面的  //localhost:9000/sayHi

server:
  port: 65000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

management:
  endpoint:
    env:
      enabled: false
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

ignore:
  jwt:
    skip-auth-urls:
      - /sayHi2